### PR TITLE
fix: enabled auth add support watsonx backend

### PR DESCRIPTION
**Pull request by gyliu513**
Closes https://github.com/k8sgpt-ai/k8sgpt/issues/1189

## 📑 Description
```console
gyliu@Guangyas-MacBook-Air k8sgpt % ./bin/k8sgpt auth add --backend watsonxai --providerId xxxxxxxxxx
Warning: model input is empty, will use the default value: gpt-3.5-turbo
Enter watsonxai Key: watsonxai added to the AI backend provider list
```

```console
gyliu@Guangyas-MacBook-Air k8sgpt % bin/k8sgpt analyze --explain --backend watsonxai
 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (7/7, 2457 it/s)
AI Provider: watsonxai

0: Node instana-0()
- Error: instana-0 has condition of type EtcdIsVoter, reason MemberNotLearner: Node is a voting member of the etcd cluster


Error: etcd is a distributed, consistent key-value store that is used to store and retrieve data across a cluster of machines. When etcd is in a condition where it is a voting member and a member is not learning, it means that the node is unable to keep up with the cluster's consensus algorithm.

Solution: To resolve this issue, you should first check the etcd logs to identify any error messages or warnings related to the member not learning. If no such messages are present, you can try restarting the etcd member process on the affected node. This can be done by running the command "etcdctl member-list" and checking if the node is listed as a member. If it is not, you can restart the etcd member process using the command "etcdctl start".

Additionally, you can also ensure that the node has the latest etcd version installed. If the issue persists, you may need to contact the etcd support team for further assistance.

It's important to note that maintaining a healthy etcd cluster is crucial for the overall stability of your Kubernetes environment. Regularly monitoring etcd health and performance can help prevent such issues from occurring.
```

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [X] All the tests have passed

### CODE REVIEW

**Review by JuHyung-Son — APPROVED** [review]
LGTM

**Comment by gyliu513** [comment]
> and why hide the projectId?

@JuHyung-Son I did not hide it, just remove it from here, as it is my own project id, updated it now using `xxxx`, hope it is ok. thanks!

**Comment by AlexsJones** [comment]
I wanted to clarify this change as I don't have the ability to test it.
Was the previous version wrong or out of date? @gyliu513

**Comment by gyliu513** [comment]
> I wanted to clarify this change as I don't have the ability to test it.
Was the previous version wrong or out of date? @gyliu513

@AlexsJones The previous version is right, but the only problem is it request end user to set env vars for apikey and project id, this enhancement is trying to follow the pattern of k8sgpt to set apikey and projectid when adding auth, hope it is OK, thanks.

**Comment by gyliu513** [comment]
@matthisholleville done, using `providerId` instead, thanks!

**Review by matthisholleville — APPROVED** [review]
lgtm

**Pull request merged**
