### PR TITLE
chore: gofmt fix and enable in CI

### PR DESCRIPTION
**Pull request by panpan0000**
Closes #NA

## 📑 Description

Fix some files detected by `make fmt`
Add `make test` and `make fmt` into Github Action. `make lint` is not added until all lint problems fixed(refer to comment in https://github.com/k8sgpt-ai/k8sgpt/pull/405)

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [NA] My code requires changes to the documentation
- [NA] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by panpan0000** [comment]
@cubxxw can you please help to review, as a CI expert ?

I'm not sure if the `make` command will work in Github Action (but seems no way to test it unless merge it), can you help me to confirm ?

thank you so much.

**Review by cubxxw — COMMENTED** [review]
@panpan0000 
Of course, there's no problem with unit tests, and we might need to add a test coverage later on. The Fmt isn't particularly elegant, and the cicd seems to just skip the actions and pass.
+ [https://github.com/k8sgpt-ai/k8sgpt/actions/runs/4975489452/jobs/8902704352?pr=414](https://github.com/k8sgpt-ai/k8sgpt/actions/runs/4975489452/jobs/8902704352?pr=414)
image

**Review by AlexsJones — APPROVED** [review]

**Comment by panpan0000** [comment]
Hmm... Thanks for both of you...
@cubxxw,about the reason why the `fmt` pass ,  all files are align with gofmt, so `make gofmt` returns nothing. Am I right ?

**Comment by cubxxw** [comment]
> Thanks for both of you... @cubxxw:
> 
> 1. about the reason why the `fmt` pass ,  all files are align with gofmt, so `make gofmt` returns nothing. Am I right ?
> 2. Can you help about how to refine the checking for `make fmt`. you are right, my code looks ugly...

Since there is no change in itself, make fmt may be due to nothing being executed, so there is no corresponding, and you are right.

I will keep this in mind later in the design of the CICD stream. Thank you for trusting me

**Pull request merged**
