### PR TITLE
feat: added Google GenAI client; simplified IAI/clients API surface.

### PR DESCRIPTION
**Pull request by bwplotka**
## 📑 Description

**Disclaimer**: I am not a GenAI experts, or official Google delegate around those topics. I know what you know from public docs (: I am simply contributing some improvements here as I experiment with the OSS tooling around analyzing Kubernetes problems. Thought I could improve some CNCF software on the way.

This PR adds the newest https://ai.google.dev/ API (for [Gemini and PaLM (legacy) models](https://ai.google.dev/models)).

I think it *might be* fixing https://github.com/k8sgpt-ai/k8sgpt/issues/799, since the Gemini API added here is also supported by [Google Cloud Vertex AI](https://cloud.google.com/vertex-ai?hl=en) but there is no Vertex AI client/API per se (AFAIK), there was only PaLM APIs, so not sure. Sorry @swastik959 if I accidentally solved the issue you were assigned to. I had to do this work anyway for my experiments.

On the way I couldn't understand why `IAI` interface is so complex. After investigation it seems it might be some tech debt from initial experiments, I proposed some changes to limit code duplication, improve readability and consistency (and fixed some gaps on the way). Specifically:

* `add auth` flags specify which backend cares about which settings
* AI clients are not expected to parse multiple "failure texts", process prompt template and cache. This is common behavior that might be better to be implemented once on Analysis function. This fixed numerous existing bugs with some providers/clients which had inconsistent logic for that (lack of caching/lack of processing/caching is not best effort etc). This was offloaded to one `getAIResultForSanitizedFailures` function. Thanks of that `GenerateComplete` is trvial and `Parse` can be removed. 
* AI clients are not aware of  `language`. Current code only tries to force language with prompt prefix, so no need to inject it (we can inject later if needed). This simplifies `Configure` method.

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [X] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

Gemini API is still rolling out e.g. it's not available in UK yet 🙈 Full details: https://ai.google.dev/available_regions

### CODE REVIEW

**Review by arbreezy — APPROVED** [review]
Great work thanks @bwplotka.

Lgtm although I can't test the new backend.
One minor thing,  our semantic PR validation fails if you have a capital letter after the prefix.

**Comment by bwplotka** [comment]
Done, thanks!

**Review by matthisholleville — CHANGES_REQUESTED** [review]
Thank you @bwplotka for your contribution ! Good job ! Shouldn't we add an example in the readme? https://github.com/k8sgpt-ai/k8sgpt/blob/main/README.md#key-features

**Comment by bwplotka** [comment]
Yup, I can do that in later PR or this one, up to you. Tomorrow though, closing laptop for today!

**Review by thschue — APPROVED** [review]
lgtm

**Comment by thschue** [comment]
> Yup, I can do that in later PR or this one, up to you. Tomorrow though, closing laptop for today!

Please open a new PR for the docs

Thank you for this contribution!

**Comment by bwplotka** [comment]
Thanks! Docs in progress 💪🏽

**Pull request merged**
