### PR TITLE
feat: skip k3s node type `EtcdIsVoter`

### PR DESCRIPTION
**Pull request by yankay**
Closes  https://github.com/k8sgpt-ai/k8sgpt/issues/1166

## 📑 Description

Skip k3s node Condition EtcdIsVoter Status reported as an error.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Review by JuHyung-Son — COMMENTED** [review]
does this error is only specific to k3s?

**Comment by yankay** [comment]
> does this error is only specific to k3s?

Yes, it's only for k3s

**Review by JuHyung-Son — COMMENTED** [review]
How about define `ignore []string` and put this error in it.
Then, case if NodeConditionType is in ignore, break.

**Comment by AlexsJones** [comment]
I am inclined to agree that if this unblocks errors in k3s then we should add it. 

Anyone else @k8sgpt-ai/k8sgpt-maintainers  ?

**Comment by arbreezy** [comment]
no objections from my side, looks safe :) @AlexsJones

**Pull request merged**
