### PR TITLE
docs: fix Slack link

### PR DESCRIPTION
**Pull request by hdm23061993**
Fixes issue #232 

## 📑 Description
- Updated Slack link
- Fixed missing `<details>` closure in README.md

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Review by matthisholleville — APPROVED** [review]

**Review by thschue — CHANGES_REQUESTED** [review]
Currently not sure if this is the way to go ...

**Comment by hdm23061993** [comment]
Isn;t there a generic link which can be used here?

**Comment by hdm23061993** [comment]
That should be the permanent solution to this

**Comment by AlexsJones** [comment]
Is there a way I can allow auto joins?

**Review by AlexsJones — APPROVED** [review]

**Comment by AlexsJones** [comment]
Approving until we have a better solution

**Pull request merged**
