### PR TITLE
fix: set result name and namespace to trivy vulnreport and configaudi…

### PR DESCRIPTION
**Pull request by jkleinlercher**
Closes https://github.com/k8sgpt-ai/k8sgpt-operator/issues/240 and replaces #678

## 📑 Description
this is the better approach to fix https://github.com/k8sgpt-ai/k8sgpt-operator/issues/240 by using the resource name and namespace of the trivy ConfigAuditReport and VulnerabilityReport

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Review by AlexsJones — APPROVED** [review]

**Comment by jkleinlercher** [comment]
Thanks for your approval @AlexsJones . Could you please merge it, too? Thank you!

**Comment by AlexsJones** [comment]
Mind taking a look at the linter issue locally @jkleinlercher ?

**Comment by jkleinlercher** [comment]
> Mind taking a look at the linter issue locally @jkleinlercher ?

I needed to increase the timeout in https://github.com/k8sgpt-ai/k8sgpt/pull/869/commits/5840b8ed8dc9bfea818317fa861e679907c734a6 . Don't know why this is needed, but I saw you also already increased the timeout.

**Comment by jkleinlercher** [comment]
@AlexsJones would merge this? Would be great to have this in the next release :)

**Pull request merged**
