### PR TITLE
docs: add installation guide using rpm, deb, apk

### LINKED ISSUE #202: docs: create documentation for installation via rpm, deb, apk
Checklist:
* [X] I've searched for similar issues and couldn't find anything matching
* [X] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [X] No

## Describe the solution you'd like
With version [0.1.8](https://github.com/k8sgpt-ai/k8sgpt/releases/tag/v0.1.8), we started building packages for various distributions. Therefore, the installation process should get documented.

### PR DESCRIPTION
**Pull request by rakshitgondwal**
Closes #202 

## 📑 Description
Added installation guide using `rpm`, `deb`, `apk` in the `README.md`

A preview can be seen over [here](https://github.com/rakshitgondwal/k8sgpt/tree/docs#installation).

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by AlexsJones** [comment]
Looking at the preview, it's a bit excessive, can we have these things in a drop down or some other link to "additional installation options" in the docs?

**Comment by rakshitgondwal** [comment]
Yes! We can make these changes to this [file](https://github.com/k8sgpt-ai/docs/blob/main/docs/getting-started/installation.md) and then have something like `Installation` redirecting to this file. But if to move the installation guide to some other file then I think we should also consider moving the `Quick start`, `Usage`, and other stuff to the docs too.

**Comment by thschue** [comment]
You could hide this in details blocks for deb, apk and rpm, think the primary installation method should stay brew, therefore it’s ok to not have the others there prominently…

**Comment by thschue** [comment]
Please also add a curl/wget command to download the respective package. Furthermore, please add the release-please annotations to update the version in the scripts, e.g. automatically:

```
<!---x-release-please-start-version-->
  - Download package: [k8sgpt_amd64.rpm](https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.1.8/k8sgpt_amd64.rpm)
<!---x-release-please-end-->
```

**Comment by rakshitgondwal** [comment]
Do you mean something like this? 
```
<!---x-release-please-start-version-->

curl -LO https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.1.8/k8sgpt_amd64.rpm

<!---x-release-please-end-->
```

**Review by thschue — APPROVED** [review]
good work! lgtm

**Review by AlexsJones — APPROVED** [review]

**Comment by rakshitgondwal** [comment]
Thank you for the merge!

**Pull request merged**
