### PR TITLE
feat: getting the error from status field for HPA analyzer

### PR DESCRIPTION
**Pull request by naveenthangaraj03**
Display the error from the status field, will get to know the clear error from the HPA 

Closes # 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by JuHyung-Son** [comment]
overall looks good!
would you add test for this?

**Comment by naveenthangaraj03** [comment]
@JuHyung-Son 
No, I am not aware of that

**Review by AlexsJones — APPROVED** [review]

**Review by AlexsJones — CHANGES_REQUESTED** [review]
Please fix these tests
```
--- FAIL: TestHPAAnalyzerWithUnsuportedScaleTargetRef (0.00s)
    hpaAnalyzer_test.go:130: expected error 'does not possible option.' not found in analysis results
--- FAIL: TestHPAAnalyzerWithNonExistentScaleTargetRef (0.00s)
    hpaAnalyzer_test.go:177: expected error 'does not exist.' not found in analysis results
	assert.go:24: got 0 want 1 

```

**Comment by naveenthangaraj03** [comment]
@AlexsJones Can you check this once?

**Comment by matthisholleville** [comment]
HI @naveenthangaraj03 ! Tests not worked with your change https://github.com/k8sgpt-ai/k8sgpt/actions/runs/10019909423/job/27696980225?pr=1164

**Comment by naveenthangaraj03** [comment]
@matthisholleville Can you check this now?

**Review by AlexsJones — APPROVED** [review]

**Review by matthisholleville — APPROVED** [review]
lgtm

**Pull request merged**
