### PR TITLE
chore: update homebrew installation note

### PR DESCRIPTION
**Pull request by chenrui333**
## 📑 Description

chore: update homebrew installation note

This would be the formula page, https://formulae.brew.sh/formula/k8sgpt (after analytics update)

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

relates to https://github.com/Homebrew/homebrew-core/pull/159089

### CODE REVIEW

**Comment by AlexsJones** [comment]
Thanks for this, I hadn't realised it had actually been contributed to homebrew formula mainline, which is why we ran a tap.

**Comment by AlexsJones** [comment]
Please resolve conficts

**Comment by chenrui333** [comment]
should be good now.

**Comment by chenrui333** [comment]
> Thanks for this, I hadn't realised it had actually been contributed to homebrew formula mainline, which is why we ran a tap.

yeah, make sense to me.

**Comment by AlexsJones** [comment]
> > Thanks for this, I hadn't realised it had actually been contributed to homebrew formula mainline, which is why we ran a tap.
> 
> yeah, make sense to me.

How will this be updated when we have a new release?

**Comment by chenrui333** [comment]
> > > Thanks for this, I hadn't realised it had actually been contributed to homebrew formula mainline, which is why we ran a tap.
> > 
> > 
> > yeah, make sense to me.
> 
> How will this be updated when we have a new release?

you can add this action into your release flow, that should be it, happy to help.

**Comment by AlexsJones** [comment]
> > > > Thanks for this, I hadn't realised it had actually been contributed to homebrew formula mainline, which is why we ran a tap.
> > > 
> > > 
> > > yeah, make sense to me.
> > 
> > 
> > How will this be updated when we have a new release?
> 
> you can add [this action](https://github.com/mislav/bump-homebrew-formula-action) into your release flow, that should be it, happy to help.

Thanks,
Should that be part of this PR?

**Comment by chenrui333** [comment]
> > > > > Thanks for this, I hadn't realised it had actually been contributed to homebrew formula mainline, which is why we ran a tap.
> > > > 
> > > > 
> > > > yeah, make sense to me.
> > > 
> > > 
> > > How will this be updated when we have a new release?
> > 
> > 
> > you can add [this action](https://github.com/mislav/bump-homebrew-formula-action) into your release flow, that should be it, happy to help.
> 
> Thanks, Should that be part of this PR?

No it should be separate PR, even we dont do per this PR, it would have homebrew maintainers/contributors updating them in patch.

Also for the action setup, it does require committer_token stuff.

**Comment by chenrui333** [comment]
@AlexsJones why did you close this?

**Comment by chenrui333** [comment]
FYI, these are the recent updates, https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+k8sgpt

**Comment by AlexsJones** [comment]
Hi, apologies this was done in error @chenrui333

**Comment by chenrui333** [comment]
Oh, no worries, :)

**Comment by chenrui333** [comment]
@AlexsJones thanks for the approval, any process of getting this merged? :)

**Comment by AlexsJones** [comment]
I can't merge this until we have an action to auto update the brew core repository. Otherwise next release we will go out of date.  It looks like currently it's relying on manual PR's to homebred-core which I don't want to have to rely on

**Comment by chenrui333** [comment]
@AlexsJones just raised a homebrew release integration PR, let me know if that works for you

using this action, https://github.com/mislav/bump-homebrew-formula-action

some examples, https://github.com/cli/cli/blob/trunk/.github/workflows/homebrew-bump.yml

**Pull request closed without merging**
