### PR TITLE
fix: --kubeconfig doesn't work

### LINKED ISSUE #604: [Bug]: `--kubeconfig` doesn't work
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

k8sgpt: 0.3.7 (1bc0f42), built at: unknown

### Kubernetes Version

v1.27.0

### Host OS and its Version

_No response_

### Steps to reproduce

1. In a cluster
2. export another KUBECONFIG
3. Run the `k8sgpt --kubeconfig=/tmp/kubeconfig-3608642416 analyze -aed`

### Expected behaviour

It should use the `KUBECONFIG` when users export it.

### Actual behaviour

The cluster we export.
```console
$ oc config get-contexts
CURRENT   NAME    CLUSTER                AUTHINFO   NAMESPACE
*         admin   ci-op-1fym1gz3-564bf   admin  
$ oc whoami
system:admin
```
But, it still read the `InClusterConfig` config, not the specific `KUBECONFIG`
```console
k8sgpt --kubeconfig=/tmp/kubeconfig-3608642416 analyze -aed
AI Provider: openai

Warnings : 
- [MutatingWebhookAnalyzer] mutatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:ci-op-1fym1gz3:aws-ipi-ovn-efs-fips-f14" cannot list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
- [NodeAnalyzer] nodes is forbidden: User "system:serviceaccount:ci-op-1fym1gz3:aws-ipi-ovn-efs-fips-f14" cannot list resource "nodes" in API group "" at the cluster scope
- [StatefulSetAnalyzer] statefulsets.apps is forbidden: User "system:serviceaccount:ci-op-1fym1gz3:aws-ipi-ovn-efs-fips-f14" cannot list resource "statefulsets" in API group "apps" at the cluster scope
- [ValidatingWebhookAnalyzer] validatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:ci-op-1fym1gz3:aws-ipi-ovn-efs-fips-f14" cannot list resource "validatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
- [PodAnalyzer] pods is forbidden: User "system:serviceaccount:ci-op-1fym1gz3:aws-ipi-ovn-efs-fips-f14" cannot list resource "pods" in API group "" at the cluster scope
- [IngressAnalyzer] ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:ci-op-1fym1gz3:aws-ipi-ovn-efs-fips-f14" cannot list resource "ingresses" in API group "networking.k8s.io" at the cluster scope
- [PvcAnalyzer] persistentvolumeclaims is forbidden: User "system:serviceaccount:ci-op-1fym1gz3:aws-ipi-ovn-efs-fips-f14" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope
- [CronJobAnalyzer] cronjobs.batch is forbidden: User "system:serviceaccount:ci-op-1fym1gz3:aws-ipi-ovn-efs-fips-f14" cannot list resource "cronjobs" in API group "batch" at the cluster scope
- [ServiceAnalyzer] endpoints is forbidden: User "system:serviceaccount:ci-op-1fym1gz3:aws-ipi-ovn-efs-fips-f14" cannot list resource "endpoints" in API group "" at the cluster scope
- [ReplicaSetAnalyzer] replicasets.apps is forbidden: User "system:serviceaccount:ci-op-1fym1gz3:aws-ipi-ovn-efs-fips-f14" cannot list resource "replicasets" in API group "apps" at the cluster scope
- [DeploymentAnalyzer] deployments.apps is forbidden: User "system:serviceaccount:ci-op-1fym1gz3:aws-ipi-ovn-efs-fips-f14" cannot list resource "deployments" in API group "apps" at the cluster scope

No problems detected
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jianzhangbjz**
Closes #604 

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
Hi @AlexsJones could you help review it when you get a chance? Thanks!

**Review by arbreezy — APPROVED** [review]
LGTM

**Comment by arbreezy** [comment]
> Hi @arbreezy , thanks for reviewing! But, could you help merge it manually? Or anything else I need to do? Thanks! Seems like it was blocked. image

we need one more approval to merge it..
maybe @matthisholleville can merge this, I don't have access on this repo

**Comment by AlexsJones** [comment]
I had to back this out as I realised that if no kubeconfig is set as a parameter, then it will assume incluster - which is not correct. For example on my local machine:

```
    ~/Code/k8sgpt    main ?1  go run ./main.go analyze                               ✔ 
Error initialising kubernetes client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
Error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

```

**Comment by jianzhangbjz** [comment]
Hi @AlexsJones , sorry, I'm a little bit confused. It works well in my local. As you know, if no `kubeconfig` is set,  it will get `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` values from ENV variables, see  https://github.com/kubernetes/client-go/blob/master/rest/config.go#L516 . So one question, did you export them on your local env? Thanks!

**Comment by jianzhangbjz** [comment]
Hi @AlexsJones , this #604 issue still exists, could you help revert #608? Or anything else I missed? Thanks! cc: @arbreezy

**Comment by arbreezy** [comment]
Hey @jianzhangbjz just a heads up, we merged a fix on this issue recently.

**Comment by jianzhangbjz** [comment]
Hi @arbreezy , got it, thanks!

**Pull request merged**
