### PR TITLE
fix: ensure ingress HTTP rule exists to prevent analyze panic

### LINKED ISSUE #653: [Bug]: Panic when analyzing ingress that has no paths (w suggested fix)
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)

### K8sGPT Version

v0.3.14

### Kubernetes Version

v1.27

### Host OS and its Version

MacOS 14 Sonoma 

### Steps to reproduce

- Create a ingress that has no paths defined yet (this use case may arise when an expert wants to configure an ingress rule with annotations and TLS secrets, while leaving defining paths for services up to developers).
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress-1
spec:
  ingressClassName: nginx
  rules:
  - host: asdf
 ```

- Run `k8sgpt analyze --filter Ingress`

### Expected behaviour

There should be a valid response with error message summaries or no errors.

### Actual behaviour

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10410719c]

goroutine 27 [running]:
github.com/k8sgpt-ai/k8sgpt/pkg/analyzer.IngressAnalyzer.Analyze({}, {0x14000703710, {0x104f0bc18, 0x14000126018}, {0x0, 0x0}, {0x104f0c350, 0x106207020}, 0x0, {0x0, ...}, ...})
	/home/runner/work/k8sgpt/k8sgpt/pkg/analyzer/ingress.go:102 +0xc3c
github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).RunAnalysis.func2({0x104eefca0?, 0x10624c6b8?}, {0x14000054240, 0x7})
	/home/runner/work/k8sgpt/k8sgpt/pkg/analysis/analysis.go:198 +0xc0
created by github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).RunAnalysis
	/home/runner/work/k8sgpt/k8sgpt/pkg/analysis/analysis.go:196 +0x7c0
```

### Additional Information

It could be worth checking if `rule.HTTP != nil` before looping through `role.HTTP.Paths` at `k8sgpt/pkg/analyzer/ingress.go:102`

### PR DESCRIPTION
**Pull request by testA113**
Closes #653 

## 📑 Description

The issue described gives a panic since the `rule.HTTP` field may not exist in an ingress object. My fix checks if the HTTP field `rule.HTTP` filed exists before looping though the `rule.HTTP.Paths`

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by AlexsJones** [comment]
Thank you for this @testA113 can you please push this as a signed commit? There are instructions inside the check that has failed for DCO with a ❌

**Comment by testA113** [comment]
Thanks @AlexsJones! I've followed the DCO instruction a couple of times, but don't seem to be triggering a new DCO test. Is there something wrong with my commit message still?

**Comment by testA113** [comment]
@AlexsJones any update?

**Comment by arbreezy** [comment]
@testA113 Ah I see, so it's complaining about your configured git email
`Commit sha: [fa09633](https://github.com/k8sgpt-ai/k8sgpt/pull/654/commits/fa096336a34994f39cf3f33dd8619864d962bf89), Author: testa113, Committer: testa113; testa113 is not a valid email address.`

ref: https://github.com/dcoapp/app/pull/35

**Comment by AlexsJones** [comment]
- In your local branch, run: git rebase HEAD~2 --signoff
- Force push your changes to overwrite the branch: git push --force-with-lease origin fix/no-ingress-paths-analyze-panic

**Pull request closed without merging**
