### PR TITLE
feat: add update to auth cmd

### LINKED ISSUE #388: [Feature]: Enhance Auth command
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

Auth could allow the user to update a previously configured provider. At the moment "auth" allows to list providers or add a new one.
Also, there's no background check on the validity of a configured key.

### Solution Description

- add an _update_ subcommand to the auth command
- Run a background check on the the key provided towards configured provider

### Benefits

- Allow to modify a configured provider
- Make sure a provided key is valid if not generated through _generate_ command

### Potential Drawbacks

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by HatiCode**
Closes #388

## 📑 Description
This PR adds an update subcommand to the auth command, allowing to update a key in a previously configured provider e.g: password, model...
It also fixes a couple typos met along the way.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by matthisholleville** [comment]
Hello, thank you very much for your contribution. I just reviewed your PR. It seems like it implements an update method that requires setting all the fields. Imagine if the user wants to modify only the password in their configuration or the model without having to fill in all the other fields. I think it would be interesting to lean more towards this implementation.

What do you think ?

**Comment by HatiCode** [comment]
@matthisholleville indeed this is what I'm trying to achieve, now because I reused the viper.Set() method at line 74, it reimplements all default empty values from the flags declared alongside the changes one. Do you know how I could keep the change passed with a flag and leave the rest untouched ?

**Comment by matthisholleville** [comment]
Check if the flag is not empty? I don't think flags should have default values in the case of an update.

**Comment by HatiCode** [comment]
@matthisholleville I made a couple changes and it's now working, changes are only applied for the flags used. I still feel like this could use some nice refactoring at a certain point tho

**Comment by matthisholleville** [comment]
Hello @HatiCode can you please provide an example of the commande ?

**Pull request merged**
