### PR TITLE
fix: disable adding multiple openai provider

### LINKED ISSUE #1169: [BUG]: Update OpenAI API Key failed
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

v0.3.37

### Kubernetes Version

v1.21

### Host OS and its Version

_No response_

### Steps to reproduce

1. Auth with an invalid OpenAI API Key
2. Auth again with a valid OpenAI API Key

### Expected behaviour

The API Key should able to be updated

### Actual behaviour

The OpenAI API Key was not updated

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gyliu513**
Closes #1169 

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [X] All the tests have passed

### CODE REVIEW

**Comment by gyliu513** [comment]
```console
gyliu@guangyas-air k8sgpt % ./bin/k8sgpt auth add
Warning: backend input is empty, will use the default value: openai
Warning: model input is empty, will use the default value: gpt-3.5-turbo
Enter openai Key: openai added to the AI backend provider list
```
```console
gyliu@guangyas-air k8sgpt % ./bin/k8sgpt auth add
Warning: backend input is empty, will use the default value: openai
Warning: model input is empty, will use the default value: gpt-3.5-turbo
Enter openai Key: Provider with same name already exists.
```
```console
gyliu@Guangyas-MacBook-Air k8sgpt % cat k8sgpt.yaml
active_filters:
    - ValidatingWebhookConfiguration
    - Deployment
    - PersistentVolumeClaim
    - InstanaSelfHostedInstallCheck
    - StatefulSet
    - CronJob
    - ReplicaSet
    - Service
    - Node
    - MutatingWebhookConfiguration
    - InstanaSelfHostedValidate
    - Ingress
    - Pod
ai:
    providers:
        - name: openai
          model: gpt-3.5-turbo
          password: "123456"
          temperature: 0.7
          topp: 0.5
          topk: 50
          maxtokens: 2048
          customheaders: []
    defaultprovider: ""
kubeconfig: ""
kubecontext: ""
```

**Comment by AlexsJones** [comment]
Can you help me understand this issue?

**Comment by JuHyung-Son** [comment]
your intend is to make disabling auth add if there is existing one. right?

**Comment by gyliu513** [comment]
> your intend is to make disabling auth add if there is existing one. right?

**Comment by gyliu513** [comment]
@AlexsJones @JuHyung-Son any further comments for this? Thanks!

**Comment by matthisholleville** [comment]
Hi @gyliu513 ! I just tested it, and it works well. However, the CLI still prompts me to enter an API key before returning an error, since the backend already exists. Shouldn't we perform this check before displaying the `Enter openai Key` ?

**Comment by gyliu513** [comment]
@matthisholleville done

```console
gyliu@Guangyas-MacBook-Air k8sgpt % ./bin/k8sgpt auth add
Warning: backend input is empty, will use the default value: openai
Provider with same name already exists.
```

**Review by matthisholleville — APPROVED** [review]
lgtm ! Great work

**Pull request merged**
